apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: root-app-helm-approach
  name: root-app-helm-approach
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application
  project: default
  source:
    path: apps-helm-chart/apps
    repoURL: https://github.com/mabusaa/argocd-course-app-of-apps.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true
